# Generated by Django 5.2.7 on 2025-11-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='listed',
            field=models.CharField(max_length=200),
        ),
    ]
