# Generated by Django 5.2.7 on 2025-11-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_list', '0002_alter_to_do_list_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do_list',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
